config/routes.rb
Alpaga::Application.routes.draw do
  devise_for :users
  resources :formats

  root "formats#index"

end

app/models/format.rb
class Format < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :formats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
  before_action :set_format, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]
  respond_to :html, :json



  # GET /formats
  # GET /formats.json
  def index
    @formats = Format.all
  end

  # GET /formats/1
  # GET /formats/1.json
  def show
  end

  # GET /formats/new
  def new
    @format = current_user.formats.build
  end

  # GET /formats/1/edit
  def edit
  end

  def authorized_user
  @format = current_user.formats.find_by(id: params[:id])
  redirect_to formats_path, notice: "Not authorized to edit this format" if @format.nil?
end

  # POST /formats
  # POST /formats.json
  def create
    @format = current_user.formats.build(format_params)

    respond_to do |format|
      if @format.save
        format.all { redirect_to @format, notice: 'Format was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @format }
      else
        format.all { render action: 'new' }
        #format.json { render json: @format.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formats/1
  # PATCH/PUT /formats/1.json
  def update
    respond_to do |format|
      if @format.update(format_params)
        format.all { redirect_to @format, notice: 'Format was successfully updated.' }
        #format.json { head :no_content }
      else
        format.all { render action: 'edit' }
        #format.json { render json: @format.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formats/1
  # DELETE /formats/1.json
  def destroy
    @format.destroy
    respond_to do |format|
      format.html { redirect_to formats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_format
      @format = Format.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def format_params
      params.require(:format).permit(:name, :usage, :compression, :resolution, :algorithme, :ordretrame)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/views/formats/_form.html.erb
<%= form_for(@format) do |f| %>
  <% if @format.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@format.errors.count, "error") %> prohibited this format from being saved:</h2>

      <ul>
      <% @format.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :usage %><br>
    <%= f.text_field :usage %>
  </div>
  <div class="field">
    <%= f.label :compression %><br>
    <%= f.text_field :compression %>
  </div>
  <div class="field">
    <%= f.label :resolution %><br>
    <%= f.text_field :resolution %>
  </div>
  <div class="field">
    <%= f.label :algorithme %><br>
    <%= f.text_field :algorithme  %>
  </div>
  <div class="field">
    <%= f.label :ordretrame %><br>
    <%= f.text_field :ordretrame %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/formats/edit.html.erb
<h1>Editing format</h1>

<%= render 'form' %>

<%= link_to 'Show', @format %> |
<%= link_to 'Back', formats_path %>

app/views/formats/index.html.erb
<h1>Listing formats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Usage</th>
      <th>Compression</th>
      <th>Resolution</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @formats.each do |format| %>
      <tr>
        <td><%= format.name %></td>
        <td><%= format.usage %></td>
        <td><%= format.compression %></td>
        <td><%= format.resolution %></td>
        <td><%= link_to 'Show', format %></td>
        <% if format.user == current_user %>
        <td><%= link_to 'Edit', edit_format_path(format) %></td>
        <td><%= link_to 'Destroy', format, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/formats/new.html.erb
<h1>New format</h1>

<%= render 'form' %>

<%= link_to 'Back', formats_path %>

app/views/formats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @format.name %>
</p>

<p>
  <strong>Usage:</strong>
  <%= @format.usage %>
</p>

<p>
  <strong>Compression:</strong>
  <%= @format.compression %>
</p>

<p>
  <strong>Resolution:</strong>
  <%= @format.resolution %>
</p>

<%= link_to 'Edit', edit_format_path(@format) %> |
<%= link_to 'Back', formats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alpaga</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>

<% if user_signed_in? %>
  <ul>
    <li><%= link_to 'Submit format', new_format_path %></li>
    <li><%= link_to 'Account', edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>